### ISSUE TITLE
Visualizzare diverse linee con orari oltre alla mappa

### ISSUE THREAD

**Issue by DavideFarina96** [pilotapazzo/IngSoftware2#13]
Questa pagina localizza l'utente e ne mostra la posizione su una mappa. Mostra inoltre i prossimi autobus che arriveranno alle fermate vicine all'utente. I dati vengono presi da un'API.

HTD: Dalla homepage si clicca sul pulsante che manda a questa pagina.  Interagendo con la mappa (e il menu sottostante), sarà possibile scegliere la fermata di cui avere le informazioni.

**Comment by gianlucapasqua** [comment]
Visualizzazione prossimi autobus separatamente con linea del bus, fermata corrispondente, e orario di arrivo del bus sotto la mappa.

HTD: mostrare la pagina e verificare la presenza delle fermate.
