### ISSUE TITLE
Dalla pagina Orari corsi voglio poter ottenere gli orari dei corsi che si tengono nel dipartimento di Povo

### ISSUE THREAD

**Issue by francescobruschetti** [pilotapazzo/IngSoftware2#29]
Aggiornare il server per supportare le richieste fatte dalla pagina "orari corsi" riguardo agli orari delle lezioni.
Nella pagina "orari corsi" l'utente può controllare gli orari delle lezioni del suo corso, selezionandolo da una lista

**Comment by caterinab** [comment]
La richiesta per il momento è statica
