### ISSUE TITLE
API

### ISSUE THREAD

**Issue by francescobruschetti** [pilotapazzo/IngSoftware2#4]
Per ogni pagine e categoria, trovare delle api o dei modi per ottenere le relative informazioni
- localizzazione utente
- visualizzazione stazioni bus su mappa 
- orari degli autobus 
- orari aule / lezioni
- eventi / feste
- calcola percorso da posizione utente ad una fermata selezionata

**Comment by DavideFarina96** [comment]
Ho ricreato i vari issues, questo è diventato inutile. Guardare quelle nuove.
