### ISSUE TITLE
Definire i ruoli

### ISSUE THREAD

**Issue by francescobruschetti** [pilotapazzo/IngSoftware2#6]
Chi farà che cosa durante il progetto

**Comment by DavideFarina96** [comment]
Cose generali:
- Prendere dati da API
- Creare API per dare dati all'esterno
- Gestione cookie/database per il salvataggio dei preferiti
- Creazione e gestione server node.js/heroku
Pagine:
- Creazione pagina iniziale/home
- Creazione pagina con mappa, autobus e localizzazione
- Creazione chat con gestione del parsing delle domande e risposte del bot
- Creazione pagina orari aule
- Creazione pagina in cui si vedono i preferiti (o integrazione nella home)
- Creazione pagina con calendario e possibilità di aggiungere eventi
