### ISSUE TITLE
Definire l'Organizazione

### ISSUE THREAD

**Issue by francescobruschetti** [pilotapazzo/IngSoftware2#7]
- Github Repository set up
- Branching strategy agreed
- Stories defined and mapped to 2 releases
- Agreed means of communication inside the team (eg, google group)

**Comment by DavideFarina96** [comment]
Github Repository set up
Fatto

Branching strategy agreed
Useremo il branch master per praticamente ogni cosa

Stories defined and mapped to 2 releases
Abbiamo creato le 2 release "90%" e "100%" di completamento, a cui abbiamo assegnato le principali feature che ci saranno da sviluppare. Durante lo sviluppo potremmo aggiungerne altre (o dividerle in piu stories), oltre ad aggiungere eventuali issues legate a bug che compariranno.

Agreed means of communication inside the team (eg, google group)
Useremo un gruppo whatsapp per la comunicazione diretta. Ci vedremo di persona praticamente ogni giorno in università, e per sincronizzare le task da fare useremo waffle.io
